# Generated by Django 3.0.2 on 2020-01-04 20:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('room_number', models.IntegerField()),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
